name: Build Spoofer Artifacts
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile Logic
        run: |
          rc.exe /fo resource.res resource.rc
          cl.exe /O2 /MT /EHsc /D_UNICODE /DUNICODE ass.cpp resource.res /link /OUT:vlrnt_sb_spoofer.exe gdiplus.lib wininet.lib user32.lib gdi32.lib shell32.lib advapi32.lib shlwapi.lib ole32.lib
          
      - name: Upload Finished EXE
        uses: actions/upload-artifact@v4
        with:
          name: Valorant-SB-Spoofer
          path: vlrnt_sb_spoofer.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: vlrnt_sb_spoofer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Binary to CDN
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdir bin -Force
          cp vlrnt_sb_spoofer.exe bin/
          git add bin/vlrnt_sb_spoofer.exe
          git commit -m "Update binary distribution [skip ci]" || exit 0
          git push origin main
