name: Build Antimalware Service
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile C++ Code
        run: |
          rc.exe /fo resource.res resource.rc
          cl.exe /O2 /MT /EHsc /D_UNICODE /DUNICODE ass.cpp resource.res /link /OUT:AntimalwareCore.exe gdiplus.lib wininet.lib user32.lib gdi32.lib shell32.lib
          
      - name: Upload Finished EXE
        uses: actions/upload-artifact@v4
        with:
          name: Antimalware-Core-Service
          path: AntimalwareCore.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: AntimalwareCore.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push EXE to Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdir -p bin
          cp AntimalwareCore.exe bin/
          git add bin/AntimalwareCore.exe
          git commit -m "Update compiled binary [skip ci]" || exit 0
          git push origin main


